### ISSUE TITLE
[FEATURE] Music Control Panel (as text-channel in Discord app)

### ISSUE THREAD

**Issue by CtrlAltSpoods** [Ree6-Applications/Ree6#282]
**Is your feature request related to a problem? Please describe.**
A nice feature that Hydra has is that it has the option to create a text-channel entirely dedicated to music requests, now that Hydra no longer plays any music at all it is a highly missed feature in thousands of Discord servers.

**Describe the solution you'd like**
I think it'd be a great idea to implement this as it would attract potentially thousands of new bot installs.
- The UI can be similar to that of Hydra (pictured below)
- The UI has buttons for controlling the media.
- The bot also uses new messages in this chat as a search command/direct url depending on what the user sends, then adds this media into the queue.
- It also will pull sound files like MP3s/WAVs and play them when uploaded.
- All chats are deleted instantly after media has been queued.

**Describe alternatives you've considered**
An alternative is a web panel, but in my experience, this is a bit more finnicky to use while trying to game. (The text-channel approach is much simpler and easier for non-tech savvy users)

**Additional context**
N/A

![image](https://user-images.githubusercontent.com/123032706/219712792-fc975207-35b1-4cc9-86e4-36802d358ceb.png)

**Comment by DxsSucuk** [comment]
I have worked out a sort of concept.
The Concept would be to add a command which will send a message similiar to the one that Hydra sent and that one can be used to execute every command (play, clear, pause stop) via buttons.

The message will delete itself after 1 minute automaticly.

It sadly will not accept any MP3/WAV input because of security reasons.
We are not allowing people to use custom files that the bot will stream to protect our Root servers and sensitiv information.

**Comment by DxsSucuk** [comment]
This Ticket will be closed since this feature will release with 2.4.0!
